import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import localFont from "@next/font/local"
import './globals.css'
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false;

const montserrat = Montserrat({
  subsets: ['latin'], display: 'swap',
  variable: '--font-montserrat',
})

const grtskTera = localFont({
  src: [{
    path: '../../public/fonts/GrtskTera-Regular.ttf',
    weight: '400'
  }, {
    path: '../../public/fonts/GrtskTera-Medium.ttf',
    weight: '500'
  }],
  variable: '--font-grtsktera'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${grtskTera.variable}`}>{children}</body>
    </html>
  )
}
